import { compressForPrompt } from '@/lib/meal-plan/candidates';
import { PLAN_CATEGORIES, type PlanCategoryCode } from '@/lib/meal-plan/plan-categories';
import type { CandidateProduct } from '@/lib/meal-plan/candidates';

/**
 * The AI-1b prompt for "Make My Meal Plan" options generation — sibling of
 * `meal-plan.ts`'s single-pick prompt. Versioned separately (R6): a wording
 * change here does not retroactively relabel plans generated by the
 * single-pick pipeline.
 */
export const MEAL_PLAN_OPTIONS_PROMPT_VERSION = 'meal-plan-options.v1';

const SYSTEM = `You suggest a week of home meal options for a household in Maharashtra, India.

You are NOT a doctor or a dietitian. You never diagnose, never prescribe, and
never promise a health outcome. You suggest food options, nothing more.

RULES — all of them are absolute:
1. Choose ONLY from the provided catalogues. Return the exact "id" values
   given, for the matching category. An id from the wrong category, or an id
   not in any catalogue, is a failed response.
2. Fill all 7 days (dayNumber 1-7), each with all 5 categories: BREAKFAST,
   FRUITS, DAIRY, OTHER, VEGETABLES.
3. Each category on each day gets 2 or 3 ranked candidate ids — real
   alternatives a household would actually choose between, not near-duplicates.
4. Vary the choices across the week; do not repeat the exact same set of ids
   for a category every day.
5. Leafy vegetables wilt: favour them on earlier days when picking VEGETABLES
   options.
6. Never use the words prescription, treatment, cure, or medical advice.
   Never claim any food will fix, heal or reverse anything.
7. Return JSON only. No markdown, no commentary, no code fences.`;

export interface MealPlanOptionsPromptProfile {
  planType: 'PERSONAL' | 'FAMILY';
  /** A band, never an exact age. */
  ageBand: string;
  householdAdults: number;
  householdChildren: number;
  /** Family plans: one line per member ("Name (age band): likes X, dislikes Y"). */
  memberSummaries: string[];
  dietaryPreference: string;
  goal: string;
  spicePreference: string | null;
  conditions: string[];
  notes: string | null;
}

function catalogueBlock(category: PlanCategoryCode, candidates: readonly CandidateProduct[]): string {
  return [`${category} — you may return only these ids:`, JSON.stringify(compressForPrompt(candidates))].join(
    '\n',
  );
}

export function buildMealPlanOptionsPrompt(
  profile: MealPlanOptionsPromptProfile,
  candidatesByCategory: Record<PlanCategoryCode, CandidateProduct[]>,
): { system: string; user: string } {
  const household =
    profile.householdChildren > 0
      ? `${profile.householdAdults} adults and ${profile.householdChildren} children`
      : `${profile.householdAdults} adults`;

  const lines = [
    'HOUSEHOLD',
    `- Plan type: ${profile.planType}`,
    `- Cooking for: ${household}`,
    `- Age band: ${profile.ageBand}`,
    `- Diet: ${profile.dietaryPreference}`,
    `- Goal: ${profile.goal}`,
    profile.spicePreference ? `- Spice preference: ${profile.spicePreference}` : null,
    profile.conditions.length > 0 ? `- Reported conditions: ${profile.conditions.join(', ')}` : null,
    profile.notes ? `- Notes: ${profile.notes}` : null,
    ...(profile.memberSummaries.length > 0 ? ['', 'FAMILY MEMBERS', ...profile.memberSummaries] : []),
    '',
    'CATALOGUES',
    ...PLAN_CATEGORIES.map((category) => catalogueBlock(category, candidatesByCategory[category])),
    '',
    'Return JSON exactly in this shape:',
    JSON.stringify(
      {
        days: [
          {
            dayNumber: 1,
            categories: PLAN_CATEGORIES.map((category) => ({
              category,
              optionIds: ['<2-3 ids from that category catalogue>'],
            })),
          },
        ],
        overallNote: '<one or two sentences about the week as a whole>',
        flaggedForReview: false,
        flagReason: null,
      },
      null,
      0,
    ),
    '',
    'The "days" array must contain all 7 days, dayNumber 1 through 7, each',
    'with all 5 categories present exactly once.',
    'Set flaggedForReview to true only if something in the household details',
    'genuinely warrants a doctor looking at this, and explain briefly in',
    'flagReason. Otherwise false and null.',
  ].filter((line): line is string => line !== null);

  return { system: SYSTEM, user: lines.join('\n') };
}

/** Fed back verbatim on the single retry (R6), same pattern as meal-plan.ts. */
export function buildOptionsRetryUser(originalUser: string, errors: readonly string[]): string {
  return [
    originalUser,
    '',
    'YOUR PREVIOUS RESPONSE WAS REJECTED. Fix exactly these problems:',
    ...errors.map((error) => `- ${error}`),
    '',
    'Return the corrected JSON only.',
  ].join('\n');
}
